server:
  port: 9500
spring:
  cloud:
    gateway:
      discovery:
        locator:
          # 是否和服务注册与发现组件结合，设置为 true 后可以直接使用应用名称调用服务
          enabled: true
      # 路由（routes：路由，它由唯一标识（ID）、目标服务地址（uri）、一组断言（predicates）和一组过滤器组成（filters）。filters 不是必需参数。）
      routes:
        - id: auth
          uri: lb://spark-auth
          predicates:
            - Path=/api-auth/**
          filters:
            - StripPrefix=1
