server:
  port: 9500
#  servlet:
#    context-path: /api-auth
spark:
  swagger:
    enabled: true
    title: 认证中心
    description: 认证中心接口文档
    version: 1.0
    base-package: com.spark.auth.controller